runtime: python27
api_version: 1
threadsafe: true
service: notifications

handlers:
- url: /mail/.*
  script: src.mail.main.app
  secure: always
- url: /.*
  script: src.helpers.generic_errors.main.app

automatic_scaling:
  max_idle_instances: 10
