runtime: python27
api_version: 1
threadsafe: true
service: notifications

handlers:
- url: /.well-known
  static_dir: well-known

- url: /.*
  script: notifications.app
  secure: always

automatic_scaling:
  max_idle_instances: 10
